### ISSUE TITLE
star.c10r.facebook.com is a CNAME for web.facebook.com

### ISSUE THREAD

**Issue by p1r473** [12425/adblist#1]
star.c10r.facebook.com is a CNAME for web.facebook.com
Those of us who use Deep Packet Inspection will now get web.facebook.com blocked
Please remove this domain- it is a false positive. It is needed for Facebook Messenger

**Comment by 12425** [comment]
This site is included in energized-social.txt and I also find other false positives, so I exclude the list. Now it should not contain star.c10r.facebook.com.
