### ISSUE TITLE
videos-cloudflare.jwpsrv.com

### ISSUE THREAD

**Issue by p1r473** [12425/adblist#2]
False positive, needed for embedded TikTok videos in websites
Ex: https://www.dexerto.com/entertainment/viral-amazon-delivery-van-tiktok-has-the-internet-split-1685037/?amp

**Comment by p1r473** [comment]
@12425

**Comment by 12425** [comment]
Removed in 78ff50216bb86c56539eb70622276f2b8db5f423.
