### ISSUE TITLE
videos-fms.jwpsrv.com

### ISSUE THREAD

**Issue by p1r473** [12425/adblist#3]
These domains block embedded videos
Here is an example of the embedded video i could not play
https://forums.androidcentral.com/droid-bionic/130214-battery-symbol-question-mark-inside.html

**Comment by p1r473** [comment]
https://github.com/hemiipatu/PiHoleBlocklists/issues/8

**Comment by p1r473** [comment]
@12425

**Comment by 12425** [comment]
Removed in 78ff50216bb86c56539eb70622276f2b8db5f423.
